resources:
- repo: self

phases:
- phase: coverity
  displayName: 'Coverity'
  queue:
    name: 'Hosted Linux Preview'
  steps:
  - task: Docker@0
    displayName: Build
    inputs:
      action: 'Run an image'
      imageName: 'libgit2/trusty-openssl:latest'
      volumes: |
       $(Build.SourcesDirectory):/src
       $(Build.BinariesDirectory):/build
      envVars: |
       COVERITY_TOKEN=$(COVERITY_TOKEN)
      workDir: '/build'
      containerCommand: '/src/ci/coverity.sh'
      detached: false
